import type { StockItem } from './types'

export const INITIAL_ITEMS: StockItem[] = [
  // === Raw Food ===
  { id: 'r1',  nameTh: 'มันหมู',       nameEn: 'Pork Fat',             unit: 'kg',   category: 'raw',       supplier: '-', parLevel: 0, costPerUnit: 0, active: true },
  { id: 'r2',  nameTh: 'หมูสับ',       nameEn: 'Minced Pork',          unit: 'kg',   category: 'raw',       supplier: '-', parLevel: 0, costPerUnit: 0, active: true },
  { id: 'r3',  nameTh: 'หมูสามชั้น',   nameEn: 'Pork Belly',           unit: 'kg',   category: 'raw',       supplier: '-', parLevel: 0, costPerUnit: 0, active: true },
  { id: 'r4',  nameTh: 'สันคอหมู',     nameEn: 'Pork Neck',            unit: 'kg',   category: 'raw',       supplier: '-', parLevel: 0, costPerUnit: 0, active: true },
  { id: 'r5',  nameTh: 'สะโพกหมู',     nameEn: 'Pork Leg',             unit: 'kg',   category: 'raw',       supplier: '-', parLevel: 0, costPerUnit: 0, active: true },
  { id: 'r6',  nameTh: 'สันในไก่',     nameEn: 'Chicken Tenderloin',   unit: 'kg',   category: 'raw',       supplier: '-', parLevel: 0, costPerUnit: 0, active: true },
  { id: 'r7',  nameTh: 'เนื้อน่องไก่', nameEn: 'Chicken Drumstick',    unit: 'kg',   category: 'raw',       supplier: '-', parLevel: 0, costPerUnit: 0, active: true },
  { id: 'r8',  nameTh: 'กุ้ง',         nameEn: 'Shrimp',               unit: 'kg',   category: 'raw',       supplier: '-', parLevel: 0, costPerUnit: 0, active: true },
  { id: 'r9',  nameTh: 'หมึกกล้วย',    nameEn: 'Baby Squid',           unit: 'kg',   category: 'raw',       supplier: '-', parLevel: 0, costPerUnit: 0, active: true },
  { id: 'r10', nameTh: 'ใบกะเพราขาว',  nameEn: 'White Holy Basil',     unit: 'kg',   category: 'raw',       supplier: '-', parLevel: 0, costPerUnit: 0, active: true },
  { id: 'r11', nameTh: 'กะหล่ำปลี',    nameEn: 'Cabbage',              unit: 'kg',   category: 'raw',       supplier: '-', parLevel: 0, costPerUnit: 0, active: true },
  { id: 'r12', nameTh: 'ต้นหอม',       nameEn: 'Spring Onion',         unit: 'kg',   category: 'raw',       supplier: '-', parLevel: 0, costPerUnit: 0, active: true },
  { id: 'r13', nameTh: 'แตงกวา',       nameEn: 'Cucumber',             unit: 'kg',   category: 'raw',       supplier: '-', parLevel: 0, costPerUnit: 0, active: true },
  { id: 'r14', nameTh: 'ผักชี',        nameEn: 'Coriander',            unit: 'kg',   category: 'raw',       supplier: '-', parLevel: 0, costPerUnit: 0, active: true },
  { id: 'r15', nameTh: 'มะเขือเทศ',    nameEn: 'Tomato',               unit: 'kg',   category: 'raw',       supplier: '-', parLevel: 0, costPerUnit: 0, active: true },
  { id: 'r16', nameTh: 'มะนาว',        nameEn: 'Lime',                 unit: 'kg',   category: 'raw',       supplier: '-', parLevel: 0, costPerUnit: 0, active: true },
  { id: 'r17', nameTh: 'หอมใหญ่',      nameEn: 'Onion',                unit: 'kg',   category: 'raw',       supplier: '-', parLevel: 0, costPerUnit: 0, active: true },

  // === Freshket / Makro ===
  { id: 'fk1',  nameTh: 'เบคอน',              nameEn: 'Bacon',               unit: 'pack',   category: 'freshket', supplier: 'Freshket / Makro', parLevel: 0, costPerUnit: 0, active: true },
  { id: 'fk2',  nameTh: 'ไส้กรอก',            nameEn: 'Sausage',             unit: 'pack',   category: 'freshket', supplier: 'Freshket / Makro', parLevel: 0, costPerUnit: 0, active: true },
  { id: 'fk3',  nameTh: 'กระเทียม',           nameEn: 'Garlic',              unit: 'kg',     category: 'freshket', supplier: 'Freshket / Makro', parLevel: 0, costPerUnit: 0, active: true },
  { id: 'fk4',  nameTh: 'พริกขี้หนูสวน',     nameEn: "Bird's Eye Chili",    unit: 'kg',     category: 'freshket', supplier: 'Freshket / Makro', parLevel: 0, costPerUnit: 0, active: true },
  { id: 'fk5',  nameTh: 'ไข่ไก่',             nameEn: 'Chicken Egg',         unit: 'flat',   category: 'freshket', supplier: 'Freshket / Makro', parLevel: 0, costPerUnit: 0, active: true },
  { id: 'fk6',  nameTh: 'ไข่เป็ด',            nameEn: 'Duck Egg',            unit: 'flat',   category: 'freshket', supplier: 'Freshket / Makro', parLevel: 0, costPerUnit: 0, active: true },
  { id: 'fk7',  nameTh: 'ไข่เยี่ยวม้า',       nameEn: 'Century Egg',         unit: 'pack',   category: 'freshket', supplier: 'Freshket / Makro', parLevel: 0, costPerUnit: 0, active: true },
  { id: 'fk8',  nameTh: 'มาม่า',              nameEn: 'Instant Noodles',     unit: 'pack',   category: 'freshket', supplier: 'Freshket / Makro', parLevel: 0, costPerUnit: 0, active: true },
  { id: 'fk9',  nameTh: 'ซอสวิกกี้เขียว',    nameEn: 'Wigi Green Sauce',    unit: 'bottle', category: 'freshket', supplier: 'Freshket / Makro', parLevel: 0, costPerUnit: 0, active: true },
  { id: 'fk10', nameTh: 'ซีอิ๋วหวาน',        nameEn: 'Sweet Soy Sauce',     unit: 'bottle', category: 'freshket', supplier: 'Freshket / Makro', parLevel: 0, costPerUnit: 0, active: true },
  { id: 'fk11', nameTh: 'ซอสแม๊กกี้',        nameEn: 'Maggi Sauce',         unit: 'bottle', category: 'freshket', supplier: 'Freshket / Makro', parLevel: 0, costPerUnit: 0, active: true },
  { id: 'fk12', nameTh: 'น้ำปลาตราชั่ง',     nameEn: 'Fish Sauce (Tra Chang)', unit: 'bottle', category: 'freshket', supplier: 'Freshket / Makro', parLevel: 0, costPerUnit: 0, active: true },
  { id: 'fk13', nameTh: 'ผงชูรส',            nameEn: 'MSG',                 unit: 'pack',   category: 'freshket', supplier: 'Freshket / Makro', parLevel: 0, costPerUnit: 0, active: true },
  { id: 'fk14', nameTh: 'พริกไทยป่น',        nameEn: 'Ground Pepper',       unit: 'pack',   category: 'freshket', supplier: 'Freshket / Makro', parLevel: 0, costPerUnit: 0, active: true },
  { id: 'fk15', nameTh: 'ซอสพริก',           nameEn: 'Chili Sauce',         unit: 'bottle', category: 'freshket', supplier: 'Freshket / Makro', parLevel: 0, costPerUnit: 0, active: true },
  { id: 'fk16', nameTh: 'ซอสมะเขือเทศ',      nameEn: 'Tomato Sauce',        unit: 'bottle', category: 'freshket', supplier: 'Freshket / Makro', parLevel: 0, costPerUnit: 0, active: true },
  { id: 'fk17', nameTh: 'แป้ง savepak',      nameEn: 'Savepak Flour',       unit: 'pack',   category: 'freshket', supplier: 'Freshket / Makro', parLevel: 0, costPerUnit: 0, active: true },
  { id: 'fk18', nameTh: 'ซอสฟ้าไทย',         nameEn: 'Fah Thai Sauce',      unit: 'bottle', category: 'freshket', supplier: 'Freshket / Makro', parLevel: 0, costPerUnit: 0, active: true },
  { id: 'fk19', nameTh: 'พริกน้ำปลา aro',    nameEn: 'Aro Chili Fish Sauce', unit: 'bottle', category: 'freshket', supplier: 'Freshket / Makro', parLevel: 0, costPerUnit: 0, active: true },

  // === Franchisor ===
  { id: 'fr1', nameTh: 'เนื้อบด',          nameEn: 'Ground Beef',        unit: 'kg',   category: 'franchisor', supplier: 'Franchisor', parLevel: 0, costPerUnit: 0, active: true },
  { id: 'fr2', nameTh: 'เนื้อชิ้น',        nameEn: 'Beef Pieces',        unit: 'kg',   category: 'franchisor', supplier: 'Franchisor', parLevel: 0, costPerUnit: 0, active: true },
  { id: 'fr3', nameTh: 'หมูยอ',            nameEn: 'Pork Sausage Roll',  unit: 'pack', category: 'franchisor', supplier: 'Franchisor', parLevel: 0, costPerUnit: 0, active: true },
  { id: 'fr4', nameTh: 'กุนเชียง',         nameEn: 'Chinese Sausage',    unit: 'pack', category: 'franchisor', supplier: 'Franchisor', parLevel: 0, costPerUnit: 0, active: true },
  { id: 'fr5', nameTh: 'หน่อไม้',          nameEn: 'Bamboo Shoots',      unit: 'kg',   category: 'franchisor', supplier: 'Franchisor', parLevel: 0, costPerUnit: 0, active: true },
  { id: 'fr6', nameTh: 'พริกแห้ง',         nameEn: 'Dried Chili',        unit: 'kg',   category: 'franchisor', supplier: 'Franchisor', parLevel: 0, costPerUnit: 0, active: true },
  { id: 'fr7', nameTh: 'น้ำซอสผัด',        nameEn: 'Stir-fry Sauce',     unit: 'bottle', category: 'franchisor', supplier: 'Franchisor', parLevel: 0, costPerUnit: 0, active: true },
  { id: 'fr8', nameTh: 'กระดาษรองจาน',    nameEn: 'Plate Liner Paper',  unit: 'pack', category: 'franchisor', supplier: 'Franchisor', parLevel: 0, costPerUnit: 0, active: true },

  // === Drinks ===
  { id: 'd1',  nameTh: 'น้ำเปล่า',         nameEn: 'Water',              unit: 'pack', category: 'drinks', supplier: '-', parLevel: 0, costPerUnit: 0, active: true },
  { id: 'd2',  nameTh: 'โค้ก',             nameEn: 'Coke',               unit: 'bottle', category: 'drinks', supplier: '-', parLevel: 0, costPerUnit: 0, active: true },
  { id: 'd3',  nameTh: 'โค้กซีโร่',        nameEn: 'Coke Zero',          unit: 'bottle', category: 'drinks', supplier: '-', parLevel: 0, costPerUnit: 0, active: true },
  { id: 'd4',  nameTh: 'โค้กแคน',          nameEn: 'Coke Can',           unit: 'can',  category: 'drinks', supplier: '-', parLevel: 0, costPerUnit: 0, active: true },
  { id: 'd5',  nameTh: 'น้ำเขียว',         nameEn: 'Green Soda',         unit: 'bottle', category: 'drinks', supplier: '-', parLevel: 0, costPerUnit: 0, active: true },
  { id: 'd6',  nameTh: 'น้ำแดง',           nameEn: 'Red Soda',           unit: 'bottle', category: 'drinks', supplier: '-', parLevel: 0, costPerUnit: 0, active: true },
  { id: 'd7',  nameTh: 'น้ำส้ม',           nameEn: 'Orange Juice',       unit: 'bottle', category: 'drinks', supplier: '-', parLevel: 0, costPerUnit: 0, active: true },
  { id: 'd8',  nameTh: 'สไปร์ท',           nameEn: 'Sprite',             unit: 'bottle', category: 'drinks', supplier: '-', parLevel: 0, costPerUnit: 0, active: true },
  { id: 'd9',  nameTh: 'น้ำส้มสแปลช',      nameEn: 'Splash Orange',      unit: 'bottle', category: 'drinks', supplier: '-', parLevel: 0, costPerUnit: 0, active: true },
  { id: 'd10', nameTh: 'ชเวปส์กระป๋อง',   nameEn: 'Schweppes Can',      unit: 'can',  category: 'drinks', supplier: '-', parLevel: 0, costPerUnit: 0, active: true },

  // === ETC ===
  { id: 'e1',  nameTh: 'ข้าวสาร',          nameEn: 'Rice',               unit: 'kg',   category: 'etc', supplier: '-', parLevel: 0, costPerUnit: 0, active: true },
  { id: 'e2',  nameTh: 'กระทะ',            nameEn: 'Pan / Wok',          unit: 'piece', category: 'etc', supplier: '-', parLevel: 0, costPerUnit: 0, active: true },
  { id: 'e3',  nameTh: 'กระดาษร้อน',      nameEn: 'Wax Paper',          unit: 'roll', category: 'etc', supplier: '-', parLevel: 0, costPerUnit: 0, active: true },
  { id: 'e4',  nameTh: 'ทิชชูม้วน',       nameEn: 'Toilet Roll',        unit: 'roll', category: 'etc', supplier: '-', parLevel: 0, costPerUnit: 0, active: true },
  { id: 'e5',  nameTh: 'ทิชชูลูกค้า',    nameEn: 'Customer Tissue',    unit: 'pack', category: 'etc', supplier: '-', parLevel: 0, costPerUnit: 0, active: true },
  { id: 'e6',  nameTh: 'ถุง 8x16',        nameEn: 'Bag 8x16',           unit: 'pack', category: 'etc', supplier: '-', parLevel: 0, costPerUnit: 0, active: true },
  { id: 'e7',  nameTh: 'น้ำยาล้างจาน',    nameEn: 'Dish Soap',          unit: 'bottle', category: 'etc', supplier: '-', parLevel: 0, costPerUnit: 0, active: true },
  { id: 'e8',  nameTh: 'น้ำยาถูพื้น',     nameEn: 'Floor Cleaner',      unit: 'bottle', category: 'etc', supplier: '-', parLevel: 0, costPerUnit: 0, active: true },
  { id: 'e9',  nameTh: 'น้ำยาล้างห้องน้ำ', nameEn: 'Toilet Cleaner',    unit: 'bottle', category: 'etc', supplier: '-', parLevel: 0, costPerUnit: 0, active: true },
  { id: 'e10', nameTh: 'ผงซักฟอก',        nameEn: 'Detergent Powder',   unit: 'pack', category: 'etc', supplier: '-', parLevel: 0, costPerUnit: 0, active: true },
  { id: 'e11', nameTh: 'แก้วน้ำ',         nameEn: 'Water Glass',        unit: 'piece', category: 'etc', supplier: '-', parLevel: 0, costPerUnit: 0, active: true },
  { id: 'e12', nameTh: 'หลอด',            nameEn: 'Straw',              unit: 'pack', category: 'etc', supplier: '-', parLevel: 0, costPerUnit: 0, active: true },
  { id: 'e13', nameTh: 'กล่องขาวแบบ 2 ช่อง', nameEn: 'White Box 2-section', unit: 'pack', category: 'etc', supplier: '-', parLevel: 0, costPerUnit: 0, active: true },
  { id: 'e14', nameTh: 'กล่องข้าวแบบ 1 ช่อง', nameEn: 'Rice Box 1-section', unit: 'pack', category: 'etc', supplier: '-', parLevel: 0, costPerUnit: 0, active: true },
  { id: 'e15', nameTh: 'ช้อนส้อม',        nameEn: 'Fork & Spoon',       unit: 'pack', category: 'etc', supplier: '-', parLevel: 0, costPerUnit: 0, active: true },
]
